### ISSUE TITLE
Compatibility with PHP 8.1.x

### ISSUE THREAD

**Issue by dinamic** [reactphp-parallel/reactphp-parallel#53]
I've been trying to figure out a release that's compatible with PHP 8.1.x, but couldn't find one.

What's the suggested approach to use for PHP 8.1.x, please?

**Comment by WyriHaximus** [comment]
> I've been trying to figure out a release that's compatible with PHP 8.1.x, but couldn't find one.

There hasn't been one yet, need to finish updating https://github.com/reactphp-parallel/worker-pool before a new release will be tagged.

> What's the suggested approach to use for PHP 8.1.x, please?

You can use `react-parallel/react-parallel:^2@dev` for now. Releases should happen within a few weeks.

**Comment by dinamic** [comment]
@WyriHaximus looking at composer.json it seems to require PHP 8.2, but we're with 8.1 still.. 🤔

**Comment by WyriHaximus** [comment]
Ow sorry thought you meant 8.1 or higher. I can bump them down, make sure everything works on 8.1 as I'm probably using 8.2 features on certain points. Before bumping it again to 8.2 in a later minor release.

**Comment by WyriHaximus** [comment]
@dinamic Started working on adding support for PHP 8.1: https://github.com/reactphp-parallel/contracts/pull/11

**Comment by dinamic** [comment]
That'd be great to have! Thanks, @WyriHaximus 🙌

**Comment by WyriHaximus** [comment]
@dinamic Done! Let me know if you run into anything and how it works out for you. I'm hoping to release the next major version with it soon. I will probably bump it to 8.2 in the first or second minor release, but will keep supporting the 8.1 supporting minor for the foreseeable future.

**Comment by dinamic** [comment]
Awesome, thanks! 🤩

**Comment by WyriHaximus** [comment]
v2 is tagged and out with 8.1 support: https://github.com/reactphp-parallel/reactphp-parallel/releases/tag/2.0.0

FYI Will likely drop 8.1 in the next minor, or the one after it if you need certain features.
